---
title: "Air temperature heatwaves"
author: "Sam Bashevkin"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(dplyr)
library(tidyr)
library(readr)
library(lubridate)
library(ggplot2)
library(zipcodeR)
library(DT)
```

# Load data

Find zip codes of interest
```{r}
zips<-bind_rows(
  search_city('Stockton','CA'),
  search_city('Sacramento','CA'),
  search_city('West Sacramento','CA'),
  search_city('Pittsburg','CA'),
  search_city('Isleton','CA'))%>%
  select(zipcode, major_city)
```

Load temperature data
```{r}
temp_max_raw<-read_csv("data_clean/gridmet_temperature_CAzip_99to22.csv", 
                   col_types=cols_only(zip="c", date="D",
                               lat="d", lon="d", tmmx_C="d"))

temp_max<-temp_max_raw%>%
  filter(zip%in%zips$zipcode)%>%
  left_join(zips, by=c("zip"="zipcode"))%>%
  group_by(date, major_city)%>%
  summarise(temp_max=max(tmmx_C), .groups="drop")%>%
  mutate(major_city=factor(major_city, levels=c("Pittsburg", "Isleton", "West Sacramento", "Sacramento", "Stockton")),
         Month=month(date),
         Year=year(date))%>%
  group_by(Month, major_city)%>%
  mutate(temp_max_q99=quantile(temp_max, 0.99),
         temp_max_q95=quantile(temp_max, 0.95),
         temp_max_q90=quantile(temp_max, 0.90))%>%
  ungroup()%>%
  group_by(major_city)%>%
  mutate(temp_max_l1=lag(temp_max, 1, order_by=date),
         temp_max_l2=lag(temp_max, 2, order_by=date),
         heatwave_99=if_else(temp_max>temp_max_q99 & temp_max_l1>temp_max_q99 & temp_max_l2>temp_max_q99, TRUE, FALSE),
         heatwave_95=if_else(temp_max>temp_max_q95 & temp_max_l1>temp_max_q95 & temp_max_l2>temp_max_q95, TRUE, FALSE),
         heatwave_90=if_else(temp_max>temp_max_q90 & temp_max_l1>temp_max_q90 & temp_max_l2>temp_max_q90, TRUE, FALSE))%>%
  ungroup()%>%
  mutate(Month=month(Month, label=T))

heatwave_sum_month<-temp_max%>%
  group_by(major_city, Month)%>%
  summarise(freq_99=sum(heatwave_99)/n(),
            freq_95=sum(heatwave_95)/n(),
            freq_90=sum(heatwave_90)/n(),
            .groups="drop")%>%
  pivot_longer(cols = c(freq_99, freq_95, freq_90), values_to="heatwave_freq", names_to="quantile", names_prefix="freq_")%>%
  mutate(quantile=as.integer(quantile))

heatwave_sum_year<-temp_max%>%
  group_by(major_city, Year)%>%
  summarise(freq_99=sum(heatwave_99)/n(),
            freq_95=sum(heatwave_95)/n(),
            freq_90=sum(heatwave_90)/n(),
            .groups="drop")%>%
  pivot_longer(cols = c(freq_99, freq_95, freq_90), values_to="heatwave_freq", names_to="quantile", names_prefix="freq_")%>%
  mutate(quantile=as.integer(quantile))

heatwave_sum_year_month<-temp_max%>%
  group_by(major_city, Year, Month)%>%
  summarise(freq_99=sum(heatwave_99)/n(),
            freq_95=sum(heatwave_95)/n(),
            freq_90=sum(heatwave_90)/n(),
            .groups="drop")%>%
  pivot_longer(cols = c(freq_99, freq_95, freq_90), values_to="heatwave_freq", names_to="quantile", names_prefix="freq_")%>%
  mutate(quantile=as.integer(quantile))

cutoffs<-temp_max%>%
  distinct(major_city, Month, temp_max_q99, temp_max_q95, temp_max_q90)%>%
  pivot_longer(cols = c(temp_max_q99, temp_max_q95, temp_max_q90), values_to="cutoff", names_to="quantile", names_prefix="temp_max_q")%>%
  mutate(quantile=as.integer(quantile))
  
```

# Plots 

## Temperature data

```{r, fig.height=12, fig.width=10}
ggplot(temp_max, aes(x=yday(date), y=temp_max))+
  geom_point()+
  facet_grid(Year~major_city)+
  theme_bw()
```

## Heatwaves

### Plot temperature cutoffs

```{r}
ggplot(cutoffs, aes(x=Month, y=cutoff, color=quantile))+
  geom_point()+
  facet_wrap(~major_city)+
  scale_color_viridis_c(breaks=c(90, 95, 99))+
  ylab("Temperature cutoff (°C)")+
  theme_bw()+
  theme(axis.text.x=element_text(angle=45, hjust=1))
```

### Create table of temperature cutoffs

```{r}
datatable(mutate(cutoffs, cutoff=round(cutoff, 1)), rownames = FALSE, 
           options = list(lengthMenu = list(c(10,25,50,-1), c(10,25,50,"All"))))
```

### Plot temps with heat waves

```{r, fig.height=12, fig.width=10}
ggplot(temp_max, aes(x=date, y=temp_max))+
  geom_point()+
  geom_vline(data=filter(temp_max, heatwave_90), aes(xintercept=date), color="chartreuse3")+
  geom_vline(data=filter(temp_max, heatwave_95), aes(xintercept=date), color="darkorchid4")+
  geom_vline(data=filter(temp_max, heatwave_99), aes(xintercept=date), color="red")+
  facet_grid(Month~major_city)+
  theme_bw()+
  theme(axis.text.x=element_text(angle=45, hjust=1))
```

### Plot heat wave frequency by month

```{r, fig.height=9, fig.width=10}
ggplot(heatwave_sum_month, aes(x=Month, y=heatwave_freq, fill=major_city))+
  geom_bar(position=position_dodge(), stat = "identity")+
  facet_wrap(~quantile)+
  scale_y_continuous(expand=expansion(0,0))+
  scale_fill_viridis_d()+
  ylab("Heatwave frequency")+
  theme_bw()+
  theme(axis.text.x=element_text(angle=45, hjust=1), legend.position = "bottom")
```

### Plot heat wave frequency by year

```{r, fig.height=9, fig.width=10}
ggplot(heatwave_sum_year, aes(x=Year, y=heatwave_freq, fill=major_city))+
  geom_bar(position=position_dodge(), stat = "identity")+
  facet_wrap(~quantile)+
  scale_y_continuous(expand=expansion(0,0))+
  scale_fill_viridis_d()+
  ylab("Heatwave frequency")+
  theme_bw()+
  theme(axis.text.x=element_text(angle=45, hjust=1), legend.position = "bottom")
```

### Plot heat wave frequency by year and month

```{r, fig.height=9, fig.width=10}
ggplot(heatwave_sum_year_month, aes(x=Year, y=heatwave_freq, fill=major_city))+
  geom_bar(position=position_dodge(), stat = "identity")+
  facet_grid(Month~quantile)+
  scale_y_continuous(expand=expansion(0,0))+
  scale_fill_viridis_d()+
  ylab("Heatwave frequency")+
  theme_bw()+
  theme(axis.text.x=element_text(angle=45, hjust=1), legend.position = "bottom")
```
