---
title: "combine_air_water_plots"
author: "Catarina Pien"
date: '2023-06-05'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(dplyr)
library(ggplot2)
library(deltamapr)
library(readr)
library(patchwork)
```

# Make map
Read in data; Project
```{r}
my_crs<-26910
stations <- c("RRI", "CLL", "SRH", "GYS", "MRZ", "VER", "RIV", "JER")
station_order <- c("Martinez","Goodyear Slough","Collinsville", "Rio Vista", "Jersey Point", "Sacramento River At Hood", "Rough And Ready Island", "Vernalis")
air_order <- c("Pittsburg", "Isleton", "West Sacramento", "Sacramento", "Stockton")
cities <- st_read(here::here("shapefiles/SBDS city boundaries/SBDS city boundaries.shp")) # from air_heatwave_analysis.Rmd
cities_sf <- st_transform(cities, crs = my_crs) %>%
  mutate(major_city = factor(major_city, levels = air_order),
         lat=st_coordinates(st_centroid(geometry))[,"Y"],
         lon=st_coordinates(st_centroid(geometry))[,"X"],
         lat_nudge=c(0, 2.2, 0, -1.4, 0),
         lon_nudge=c(-0.9, 0.5, 0, -0.5, 1.15))

# boundaries -------------
# delta source: https://gis-california.opendata.arcgis.com/datasets/57b02f8a5e77465f902376dbd9522585_0/explore?location=38.135048%2C-121.109000%2C8.00 file created 7/21
# sm source: https://gis.data.ca.gov/datasets/643785963c664e48a8fba3f0e1506160_0/about file created 7/11/2023

delta <- st_read(here::here("data_raw/shapefiles/i03_LegalDeltaBoundary.shp")) 
sm <- st_read(here::here("data_raw/shapefiles/i03_SuisunMarshBoundary.shp"))

latlons <- read_csv("https://portal.edirepository.org/nis/dataviewer?packageid=edi.591.2&entityid=a059f5eea4f8500fe1a43566451ec593")
sta_locations_sf <- latlons %>%
  filter(Station %in% stations) %>%
  st_as_sf(coords = c("Longitude", "Latitude"),
           crs = 4326)
sta_locations_26910 <- st_transform(sta_locations_sf, crs = my_crs) %>%
  mutate(StationName = stringr::str_to_title(StationName)) %>%
  mutate(StationName = replace(StationName, StationName == "Vernalis (Usbr)", "Vernalis")) %>%
  mutate(StationName = factor(StationName, levels = station_order))

sta_cw <- sta_locations_26910 %>%
   as.data.frame() %>%
  select(Station, StationName)%>%
  mutate(StationName = factor(StationName, levels = station_order))

WW_Delta <- st_transform(WW_Delta, crs = my_crs)
WW_legal_delta <- st_transform(delta, crs = my_crs)
WW_suisun <- st_transform(sm, crs = my_crs) 

spts <- st_coordinates(WW_suisun)
smat <- matrix(c(spts[,1], spts[,2]), ncol = 2)
s.id <- chull(smat)
s.id <- c(s.id, s.id[1])
plot(s.id)
lines(smat[s.id,])
plot(concaveman::concaveman(smat, 0.01, 1))
```

Make map
```{r}
library(ggnewscale)
library(ggspatial)
(map <- ggplot() +
   # geom_sf(data = WW_Delta %>% filter(!HNAME%in% c("SAN FRANCISCO BAY")), color = "gray60", size = 1.5,  fill = "gray80") + 
    geom_sf(data = WW_Delta, color = "gray70", size = 1.5,  fill = "gray80") + 
   geom_sf(data = cities_sf, aes(fill = major_city),  alpha = 0.3 , inherit.aes = FALSE) +
   geom_sf(data = WW_legal_delta, color = "black", fill = NA, linewidth = 0.5, linetype = "dashed") + 
   # geom_sf(data = WW_suisun, color = "firebrick1", fill = NA, linewidth = 0.6, linetype = "dotted") + 
   scale_fill_viridis_d()+
   guides(fill = "none")+
   geom_label(data = cities_sf, aes(x=lon+lon_nudge, y=lat+lat_nudge, 
                                    label = paste(major_city, format(population, big.mark=","), sep="\n")),
                label.padding = unit(0.25, "lines"),
                # Isleton| Pittsburg | Sacramento | Stockton | West Sacramento 
                colour = "black",  size = 3.5, inherit.aes = FALSE, alpha=0.6)+
   new_scale_fill() +
   geom_sf(data = sta_locations_26910, aes(shape = StationName), color = "navy", size = 3.5, inherit.aes = FALSE) +
    annotate(geom = "text", x = 554000, y = 4214282,  label = "San Pablo Bay", fontface = "italic", size = 3) +
    annotate(geom = "text", x = 585000, y = 4214282,  label = "Suisun Bay", fontface = "italic", size = 3) +
    annotate(geom = "text", x = 590000, y = 4224282,  label = "Suisun Marsh", fontface = "italic", size = 3) +
   scale_shape_manual(values = c(0, 6, 8, 17, 18, 19, 14, 15))+
   scale_x_continuous(limits = c(540000, 671000)) +
    annotation_north_arrow(location = "tl", which_north = "true", 
        pad_x = unit(.05, "in"), pad_y = unit(0.1, "in"),
        style = north_arrow_fancy_orienteering,
        height = unit(1.5, "cm"),
  width = unit(2, "cm"),) +
  annotation_scale(location = "br", bar_cols = c("black", "white", "black", "white"), text_cex = 1) +
  # scale_fill_viridis_d(option = "turbo") + 
  labs(color = "Water temperature\nStations") +
  theme_bw() +
  theme(axis.title = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom"))
```

Write map
```{r}
png("figs/map_temperature_stations_v2.png", height = 7, width = 8, units = "in",
    res=300)
map
dev.off()
```



# Bring in data
```{r}
# Air
load(file = here::here("data_clean/air_temp_data_for_plots.Rdata"))
air_cutoffs = cutoffs %>%
  rename(Location = major_city) %>%
  mutate(Medium = "Air")%>% 
  mutate(date_= as.Date(doy-1, origin=paste0(1900, "-01-01")), 
              month= strftime(date_, "%m"), 
              day=strftime(date_,"%d"))
air_heatwave_dur = heatwave_dur %>%
  rename(Location= major_city,
         temp_mean = temp_appt_mean) %>%
  mutate(Medium = "Air")
air_heatwave_dur_year = heatwave_dur_year%>%
  group_by(major_city) %>%
  mutate(meanDuration = mean(duration_mean)) %>%
  ungroup()%>%
  mutate(Medium = "Air")
air_heatwave_sum_month = heatwave_sum_month %>%
  rename(Location = major_city) %>%
  mutate(Medium = "Air")
air_heatwave_sum_year = heatwave_sum_year %>%
  rename(Location = major_city)%>%
  mutate(Medium = "Air")
air_temp <- temp_appt 
air_temp_intensity <- air_temp %>%
  filter(!is.na(heatwave_90_intensity)) %>%
  group_by(major_city) %>%
  mutate(Intensity = mean(heatwave_90_intensity, na.rm = TRUE)) %>%
  ungroup() %>%
  group_by(major_city, Year, heatwave_90, Intensity) %>%
  summarize(meanIntensity = mean(heatwave_90_intensity, na.rm = TRUE),
         sd = sd(heatwave_90_intensity, na.rm = TRUE)) %>%
  ungroup() %>%
  rename(Location = major_city)%>%
  mutate(Medium = "Air")
air_intensity_month <- air_temp %>%
  filter(!is.na(heatwave_90_intensity)) %>%
  group_by(major_city) %>%
  mutate(Intensity = mean(heatwave_90_intensity, na.rm = TRUE)) %>%
  ungroup() %>%
  group_by(major_city, Month, heatwave_90, Intensity) %>%
  summarize(meanIntensity = mean(heatwave_90_intensity, na.rm = TRUE),
         sd = sd(heatwave_90_intensity, na.rm = TRUE)) %>%
  ungroup() %>%
  rename(Location = major_city)%>%
  mutate(Medium = "Air")

 rm(cutoffs, heatwave_dur, heatwave_dur_year, heatwave_sum_month, heatwave_sum_year)


# Water
load(file = here::here("data_clean/water_temp_data_for_plots.Rdata"))
w_cutoffs = cutoffs %>% left_join(sta_cw)%>%
  mutate(StationName = factor(StationName, levels = station_order))%>%
  mutate(Medium = "Water") %>%
  select(Location = StationName, doy, 
         # Month = fMonth, 
         quantile,cutoff, Medium) %>%
  mutate(date_= as.Date(doy-1, origin=paste0(1900, "-01-01")), 
              month= strftime(date_, "%m"), 
              day=strftime(date_,"%d"))
w_heatwave_dur <- heatwave_dur %>%left_join(sta_cw)%>%
  mutate(StationName = factor(StationName, levels = station_order)) %>%
  select(-Station) %>%
  select(Location = StationName, everything()) %>%
  mutate(Medium = "Water")
w_heatwave_dur_year = heatwave_dur_year%>% left_join(sta_cw)%>%
  mutate(StationName = factor(StationName, levels = station_order))%>%
  group_by(StationName) %>%
  mutate(meanDuration = mean(duration_mean)) %>%
  ungroup()%>%
  mutate(Medium = "Water")
w_heatwave_sum_month = heatwave_sum_month%>% left_join(sta_cw)%>%
  mutate(StationName = factor(StationName, levels = station_order)) %>%
  dplyr::select(Location = StationName, n, Month = fMonth, quantile, heatwave_freq) %>%
  mutate(Medium = "Water")
w_heatwave_sum_year = heatwave_sum_max_year%>% left_join(sta_cw)%>%
  mutate(StationName = factor(StationName, levels = station_order)) %>%
  select(-Station) %>%
  select(Location = StationName, everything())%>%
  mutate(Medium = "Water")
w_temp = temp_quantiles%>% left_join(sta_cw)%>%
  mutate(StationName = factor(StationName, levels = station_order))
w_temp_intensity <- w_temp %>%
  filter(!is.na(heatwave_90_intensity)) %>%
  group_by(StationName) %>%
  mutate(Intensity = mean(heatwave_90_intensity, na.rm = TRUE)) %>%
  ungroup() %>%
  group_by(StationName, Year, heatwave_90, Intensity) %>%
  summarize(meanIntensity = mean(heatwave_90_intensity, na.rm = TRUE),
         sd = sd(heatwave_90_intensity, na.rm = TRUE)) %>%
  ungroup() %>%
  rename(Location = StationName)%>%
  mutate(Medium = "Water")
w_intensity_month <- w_temp %>%
  filter(!is.na(heatwave_90_intensity)) %>%
  group_by(StationName) %>%
  mutate(Intensity = mean(heatwave_90_intensity, na.rm = TRUE)) %>%
  ungroup() %>%
  group_by(StationName, fMonth, heatwave_90, Intensity) %>%
  summarize(meanIntensity = mean(heatwave_90_intensity, na.rm = TRUE),
         sd = sd(heatwave_90_intensity, na.rm = TRUE)) %>%
  ungroup()  %>%
  rename(Location = StationName)%>%
  mutate(Medium = "Water")


heatwave_sum_month <- rbind(air_heatwave_sum_month, w_heatwave_sum_month)
heatwave_sum_year <- rbind(air_heatwave_sum_year, w_heatwave_sum_year)
cutoffs <- rbind(air_cutoffs, w_cutoffs)
cutoffs_90 <- cutoffs %>% filter(quantile == 90) 
duration <- rbind(air_heatwave_dur, w_heatwave_dur)
intensity_year <- rbind(w_temp_intensity, air_temp_intensity)

# rm(cutoffs, heatwave_dur, heatwave_dur_year, heatwave_sum_max, heatwave_sum_max_year)
# write_csv(cutoffs_90, "data_clean/cutoffs_90quantile_month_station.csv")
# write_csv(duration, "data_clean/heatwave_duration.csv")
```

```{r}
model_dat_air<-air_heatwave_sum_year%>%
  filter(quantile==90)%>%
  mutate(Year_s=(Year-mean(Year))/sd(Year))

mf1<-lm(heatwave_freq ~ Year_s * Location, data=model_dat_air)

summary(mf1)

model_dat_w<-w_heatwave_sum_year%>%
  filter(quantile==90)%>%
  mutate(Year_s=(Year-mean(Year))/sd(Year))

mf1w<-lm(heatwave_freq ~ Year_s * Location, data=model_dat_w)
mf2w<-lm(heatwave_freq ~ Year_s + Location, data=model_dat_w)


summary(mf1w)
plot(mf1w)

heatwave_sum_max_month_year<-temp_quantiles%>%
  group_by(Station, Year, fMonth)%>%
  summarise(freq_99=sum(heatwave_99)/n(),
            freq_95=sum(heatwave_95)/n(),
            freq_90=sum(heatwave_90)/n(),
            .groups="drop")%>%
  tidyr::pivot_longer(cols = c(freq_99, freq_95, freq_90), values_to="heatwave_freq", names_to="quantile", names_prefix="freq_")%>%
  mutate(quantile=as.integer(quantile))%>%
  filter(quantile == 90)

w_model_dat2<-heatwave_sum_max_month_year%>%
  filter(quantile==90)%>%
  mutate(Year_s=(Year-mean(Year))/sd(Year))

library(lmerTest)
library(lme4)
mf3w <- lmer(heatwave_freq ~ Year_s * factor(Station) + (1|fMonth), data=w_model_dat2)
summary(mf3w)
anova(mf3w, type = 2)

plot(mf3w)
```

# Make station table
```{r}
latlons_filtered <- latlons %>%
  filter(Station %in% stations) %>%
  dplyr::select(Station, StationName, Latitude, Longitude)

sta_table <-  temp_quantiles %>%
  arrange(Station, date) %>%
  group_by(Station) %>%
  summarize(StartDate = min(date),
            EndDate = max(date),
            n = n()) %>%
  left_join(latlons_filtered) %>%
  dplyr::select(Station, StationName, Latitude, Longitude, StartDate, EndDate)

# write_csv(sta_table, "data_clean/watertemp_station_table.csv")
```

```{r}
w_heatwave_dur %>%
  group_by(Location) %>%
  summarize(n = n())

heatwave_sum_month %>%
  group_by(Location, Medium) %>%
  summarize(mean = mean(heatwave_freq, na.rm = TRUE)) %>%
  arrange(Medium, mean)

heatwave_dur%>%
  group_by(Station) %>%
  summarize(mean = mean(duration, na.rm = TRUE)) %>%
  arrange(mean)

air_heatwave_dur%>%
  group_by(Location) %>%
  summarize(mean = mean(duration, na.rm = TRUE)) %>%
  arrange(mean)

intensity_year%>%
  group_by(Medium, Location) %>%
  summarize(mean = mean(meanIntensity, na.rm = TRUE)) %>%
  arrange(Medium, mean)

air_heatwave_dur%>%
  group_by(Location) %>%
  summarize(mean = mean(intensity_mean, na.rm = TRUE)) %>%
  arrange(mean)

heatwave_dur%>%
  group_by(Station) %>%
  summarize(mean = mean(intensity_mean, na.rm = TRUE)) %>%
  arrange(mean)
```


# Theme

Theme for plots
```{r}
theme_plots <- theme_bw()+
  theme(axis.text.x=element_text(angle=45, hjust=1), 
        axis.title.x = element_blank(), 
        axis.text = element_text(size = 11),
        legend.position = "bottom", 
        legend.text = element_text(size = 11),
        legend.title = element_blank(),
        plot.margin = margin(5, 40, 5, 5))
```

# Temp cutoffs
```{r}
cutoff_range<-range(c(filter(air_cutoffs, quantile==90)$cutoff, filter(w_cutoffs, quantile==90)$cutoff))

p1_air<-ggplot(filter(air_cutoffs, quantile==90), aes(x=date_, y=cutoff, color=Location))+
  geom_line(position=position_dodge(width=0.4), linewidth = 1)+
  scale_color_viridis_d(name="")+
  scale_y_continuous(breaks = seq(5, 50, 5), limits=cutoff_range) + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  labs(title = "A", y = "Apparent temperature cutoff (°C)")+
  theme_plots

p1_water<- ggplot(filter(w_cutoffs, quantile==90), 
                  aes(x=date_, y=cutoff, color=Location))+
  geom_line(position=position_dodge(width=0.4), linewidth = 1)+
  scale_color_viridis_d(name="", option = "turbo")+
   scale_y_continuous(breaks = seq(5, 50, 5), limits=cutoff_range) + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b") + 
  labs(title = "B", y = "Water temperature cutoff (°C)")+
  theme_plots

(p1 <- p1_air / p1_water)

png(file=here::here("figs/temperature_cutoffs.png"), height=7, width=8, units = "in", res = 300, pointsize = 14)
p1
dev.off()
```

# Frequency plots
```{r, fig.height=9, fig.width=10}
(p2_air<-ggplot(filter(air_heatwave_sum_month, quantile==90), aes(x=Month, y=heatwave_freq, fill=Location))+
  geom_bar(position=position_dodge(), stat = "identity")+
  scale_y_continuous(expand=expansion(0,0))+
  scale_fill_viridis_d(name="")+
  labs(title = "A", y = "Air Heatwave frequency")+
  guides(fill = guide_legend(nrow = 2, byrow = TRUE)) +
    theme_plots)

(p2_water<-ggplot(filter(w_heatwave_sum_month, quantile==90), aes(x=Month, y=heatwave_freq, fill=Location))+
  geom_bar(position=position_dodge(), stat = "identity")+
  scale_y_continuous(expand=expansion(0,0))+
  scale_fill_viridis_d(name="", option = "turbo")+
  labs(title = "C", y = "Water Heatwave frequency")+
  guides(fill = guide_legend(nrow = 4, byrow = TRUE)) +
  theme_plots)

(p2<-ggplot(filter(heatwave_sum_month, quantile==90), aes(x=Month, y=heatwave_freq, fill=Location))+
  geom_bar(position=position_dodge(), stat = "identity")+
  scale_y_continuous(expand=expansion(0,0))+
  scale_fill_viridis_d(name="", option = "turbo")+
    facet_wrap(~Medium) + 
  ylab("Heatwave frequency")+
  guides(fill = guide_legend(nrow = 3, byrow = TRUE)) +
  theme_plots)

(p2 <- p2_air / p2_water)
# png(file=here::here("figs/heatwave_month.png"), height=8, width=9, units = "in", res = 300)
# p2
# dev.off()


(p3_air<-ggplot(filter(air_heatwave_sum_year, quantile==90), aes(x=Year, y=heatwave_freq, fill=Location, color=Location))+
    geom_bar(position=position_dodge(), alpha = 0.7, stat = "identity")+
    geom_smooth(method="lm", se=F, show.legend = FALSE, size = 0.6)+
    scale_y_continuous(expand=expansion(0,0))+
   scale_x_continuous(breaks = seq(1999, 2022, 2)) +
    scale_fill_viridis_d(name="", aesthetics=c("color", "fill"))+
    labs(title = "B", y = "Air Heatwave frequency")+
  guides(color = guide_legend(nrow = 2, byrow = TRUE)) +
    theme_plots)

(p3_water<-ggplot(filter(w_heatwave_sum_year, quantile==90), aes(x=Year, y=heatwave_freq, fill=Location, color=Location))+
    geom_bar(position=position_dodge(), alpha = 0.7, stat = "identity")+
    geom_smooth(method="lm", se=F, show.legend = FALSE, size = 0.6)+
    scale_y_continuous(expand=expansion(0,0))+
   scale_x_continuous(breaks = seq(2002, 2022, 2)) +
    scale_fill_viridis_d(name="", aesthetics=c("color", "fill"), option = "turbo")+
    labs(title = "D", y = "Water Heatwave frequency")+
  guides(color = guide_legend(nrow = 4, byrow = TRUE)) +
    theme_plots)

(p3 <- p3_air / p3_water)


(p2p3 <- p2 | p3 )

# png(file=here::here("figs/heatwave_year.png"), height=8, width=9, units = "in", res = 300)
# p3
# dev.off()

png(file=here::here("figs/heatwave_freq.png"), height=7.5, width=11, units = "in", res = 300, pointsize = 10)
p2p3
dev.off()


```


# Duration plots
```{r}
(p4_air <- ggplot(air_heatwave_dur_year, aes(x=Year, y=duration_mean, ymin=duration_mean-duration_sd, 
                              ymax=duration_mean+duration_sd, color=major_city, 
                              group=interaction(Year, major_city)))+
  geom_pointrange()+
  geom_hline((aes(yintercept = meanDuration, color = major_city)), linetype = "longdash") + 
  scale_color_viridis_d(name="City")+
  facet_wrap(~major_city)+
  labs(title = "A", y = "Air Heatwave duration (days)")+
  scale_x_continuous(breaks = seq(1999, 2022, 2)) +
  theme_plots)

(p4_water <- ggplot(w_heatwave_dur_year, aes(x=Year, y=duration_mean, ymin=duration_mean-duration_sd, 
                              ymax=duration_mean+duration_sd, color=StationName, 
                              group=interaction(Year, StationName)))+
  geom_pointrange()+
  geom_hline((aes(yintercept = meanDuration, color = StationName)), linetype = "longdash") +
  scale_color_viridis_d(name="StationName", option = "turbo")+
  scale_x_continuous(breaks = seq(1999, 2022, 2)) +
  facet_wrap(~StationName)+
  labs(title = "B", y = "Water Heatwave duration (days)")+
  theme_plots)

(p4 <- p4_air / p4_water + plot_layout(heights = c(2,3)))


png(file=here::here("figs/duration_year.png"), height=10, width=10, units = "in", res = 300, pointsize = 14)
p4
dev.off()

duration_month <- duration %>%
  group_by(Medium, Location) %>%
  mutate(meanDuration = mean(duration, na.rm = TRUE)) %>%
  ungroup() %>%
  group_by(Medium, Month, Location, meanDuration) %>%
  summarize(duration_mean = mean(duration, na.rm = TRUE),
            duration_sd = sd(duration, na.rm = TRUE))  %>%
  ungroup()


(p4b_air <- ggplot(duration_month %>% filter(Medium == "Air"), aes(x=Month, y=duration_mean, ymin=duration_mean-duration_sd, 
                              ymax=duration_mean+duration_sd, color=Location, 
                              group=interaction(Month, Location)))+
  geom_pointrange()+
  geom_hline((aes(yintercept = meanDuration, color = Location)), linetype = "longdash") + 
  scale_color_viridis_d(name="City")+
  facet_wrap(~Location)+
  labs(title = "A", y = "Air Heatwave duration (days)")+
  # scale_x_continuous(breaks = seq(1999, 2022, 2)) +
  theme_plots)

(p4b_water <- ggplot(duration_month %>% filter(Medium == "Water"), aes(x=Month, y=duration_mean, ymin=duration_mean-duration_sd, 
                              ymax=duration_mean+duration_sd, color=Location, 
                              group=interaction(Month, Location)))+
  geom_pointrange()+
  geom_hline((aes(yintercept = meanDuration, color = Location)), linetype = "longdash") + 
  scale_color_viridis_d(option = "turbo")+
  facet_wrap(~Location)+
  labs(title = "B", y = "Water Heatwave duration (days)")+
  # scale_x_continuous(breaks = seq(1999, 2022, 2)) +
  theme_plots)



(p4b <- p4b_air / p4b_water + plot_layout(heights = c(2,3)))


png(file=here::here("figs/duration_months.png"), height=10, width=10, units = "in", res = 300, pointsize = 14)
p4b
dev.off()



```


# Intensity plots
```{r}
(p5_air <- ggplot(filter(air_temp_intensity, heatwave_90), 
      aes(x=Year, y=meanIntensity, ymin = meanIntensity - sd, ymax = meanIntensity + sd, 
           color=Location, group=interaction(Year, Location)))+
  geom_pointrange(shape = 17) +
   geom_hline((aes(yintercept = Intensity, color = Location)), linetype = "longdash") +
    facet_wrap(~Location) + 
  scale_color_viridis_d()+
   scale_x_continuous(breaks = seq(1999, 2022, 2)) + 
    labs(title = "A", y = "Air Heatwave Intensity")+
  theme_plots)

(p5_water <- ggplot(filter(w_temp_intensity, heatwave_90), 
       aes(x=Year, y=meanIntensity, ymin = meanIntensity - sd, ymax = meanIntensity + sd, 
           color=Location, group=interaction(Year, Location)))+
  geom_pointrange(shape = 17)+
     geom_hline((aes(yintercept = Intensity, color = Location)), linetype = "longdash") +
    facet_wrap(~Location) + 
  scale_color_viridis_d(option = "turbo")+
   scale_x_continuous(breaks = seq(2002, 2022, 2)) + 
    labs(title = "B", y = "Water Heatwave Intensity")+
  theme_plots)

(p6_air <- ggplot(filter(air_intensity_month, heatwave_90), 
      aes(x=Month, y=meanIntensity, ymin = meanIntensity - sd, ymax = meanIntensity + sd, 
           color=Location, group=interaction(Month, Location)))+
  geom_pointrange(shape = 17) +
   geom_hline((aes(yintercept = Intensity, color = Location)), linetype = "longdash") +
    facet_wrap(~Location) + 
  scale_color_viridis_d()+
   # scale_x_continuous() + 
    labs(title = "A", y = "Air Heatwave Intensity")+
  theme_plots)

(p6_water <- ggplot(filter(w_intensity_month, heatwave_90), 
         aes(x=fMonth, y=meanIntensity, ymin = meanIntensity - sd, ymax = meanIntensity + sd, 
           color=Location, group=interaction(fMonth, Location)))+
  geom_pointrange(shape = 17)+
     geom_hline((aes(yintercept = Intensity, color = Location)), linetype = "longdash") +
    facet_wrap(~Location) + 
  scale_color_viridis_d(option = "turbo")+
   # scale_x_continuous(breaks = seq(2002, 2022, 2)) + 
    labs(title = "B", y = "Water Heatwave Intensity")+
  theme_plots)

# p5_air <- ggplot(filter(air_temp, heatwave_95==1L), 
#        aes(x=Year, y=heatwave_95_intensity, fill=major_city, group=interaction(Year, major_city)))+
#   geom_boxplot()+
#   scale_fill_viridis_d(name="City")+
#    scale_x_continuous(breaks = seq(1999, 2022, 1)) + 
#     ylab("Air Heatwave Intensity")+
#   theme_plots
# 
# p5_water <- ggplot(filter(w_temp, heatwave_95==1L), 
#        aes(x=Year, y=heatwave_95_intensity, fill=StationName, group=interaction(Year, StationName)))+
#   geom_boxplot()+
#   scale_fill_viridis_d(name="StationName", option = "turbo")+
#    scale_x_continuous(breaks = seq(2002, 2022, 1)) + 
#     ylab("Water Heatwave Intensity")+
#   theme_plots

(p5 <- p5_air / p5_water + plot_layout(heights = c(2,3)))

png(file=here::here("figs/intensity_year.png"), height=10, width=10, units = "in", res = 300, pointsize = 14)
p5
dev.off()


(p6 <- p6_air / p6_water + plot_layout(heights = c(2,3)))

png(file=here::here("figs/intensity_month.png"), height=10, width=10, units = "in", res = 300, pointsize = 14)
p6
dev.off()

```


# Summary tables
## Cutoffs
```{r}
cutoffs_90 <- filter(cutoffs, quantile == 90)
cutoffs_summary <- cutoffs_90 %>% 
  group_by(Medium, month) %>%
  summarize(mean = mean(cutoff),
            se = sd(cutoff)/sqrt(n()))
```

## Frequency
```{r}
freq_month <- heatwave_sum_month %>%
  filter(quantile == 90) %>%
  mutate(days = n*heatwave_freq) %>%
  group_by(Medium) %>%
  mutate(mean_overall = mean(heatwave_freq, na.rm = TRUE)) %>%
  ungroup() %>%
  group_by(Medium, Month, mean_overall) %>%
  reframe(mean = mean(heatwave_freq, na.rm = TRUE),
          sd = sd(heatwave_freq, na.rm= TRUE),
          mean_days = mean(days, na.rm = TRUE)) %>%
  distinct() %>%
  arrange(Medium, mean)

freq_year <- heatwave_sum_year %>%
  mutate(days = n*heatwave_freq) %>%
  group_by(Medium) %>%
  mutate(mean_overall = mean(heatwave_freq, na.rm = TRUE),
         days_overall = sum(n, na.rm = TRUE) * mean_overall,
         fYear = factor(Year),
         heatwave_freq = ifelse(is.na(heatwave_freq), 0, heatwave_freq)) %>%
  ungroup() %>%
  group_by(Medium, fYear, mean_overall, days_overall) %>%
  reframe(mean = mean(heatwave_freq, na.rm = TRUE),
          sd = sd(heatwave_freq, na.rm= TRUE),
          mean_days = mean(days, na.rm = TRUE)) %>%
  distinct() %>%
  arrange(Medium, mean)
```

## Duration
```{r}
heatwave_events <- duration %>%
  group_by(Medium, Location) %>%
  summarize(n = n(),
            mean = mean(duration),
            sd = sd(duration)) %>%
  ungroup()

heatwave_events %>% group_by(Medium) %>%
  summarize(mean_events = mean(n))

duration_summary <- duration %>%
  group_by(Medium, Location) %>%
  summarize(n = n(),
            mean = mean(duration),
            sd = sd(duration))

duration_month_table <- duration %>%
  group_by(Medium) %>%
  ungroup() %>%
  group_by(Medium, Month) %>%
  summarize(duration_mean = mean(duration, na.rm = TRUE),
            duration_sd = sd(duration, na.rm = TRUE))  %>%
  ungroup() %>%
  arrange(Medium, duration_mean)

duration_year_table <- duration %>%
  group_by(Medium, Year) %>%
  summarize(duration_mean = mean(duration, na.rm = TRUE),
            duration_sd = sd(duration, na.rm = TRUE))  %>%
  ungroup()%>%
  arrange(Medium, duration_mean)
```

## Intensity
```{r}
int_month_w <- w_temp %>%
  mutate(mean_overall = mean(heatwave_90_intensity, na.rm = TRUE),
         sd_overall = sd(heatwave_90_intensity, na.rm = TRUE)) %>%
  group_by(fMonth, mean_overall, sd_overall) %>%
  reframe(mean = mean(heatwave_90_intensity, na.rm = TRUE),
          sd = sd(heatwave_90_intensity, na.rm = TRUE))
int_month_a <- air_temp %>%
  mutate(mean_overall = mean(heatwave_90_intensity, na.rm = TRUE),
         sd_overall = sd(heatwave_90_intensity, na.rm = TRUE)) %>%
  group_by(Month, mean_overall, sd_overall) %>%
  reframe(mean = mean(heatwave_90_intensity, na.rm = TRUE),
          sd = sd(heatwave_90_intensity, na.rm = TRUE))


int_year_w <- w_temp %>%
  group_by(Year) %>%
  reframe(mean = mean(heatwave_90_intensity, na.rm = TRUE),
          se = sd(heatwave_90_intensity, na.rm = TRUE)/sqrt(n()),
          median = median(heatwave_90_intensity, na.rm = TRUE)) %>%
  arrange(mean)
int_year_a <- air_temp %>%
  group_by(Year) %>%
  reframe(mean = mean(heatwave_90_intensity, na.rm = TRUE),
          se = sd(heatwave_90_intensity, na.rm = TRUE)/sqrt(n()),
          median = median(heatwave_90_intensity, na.rm = TRUE)) %>%
  arrange(mean)
```

```{r}
ggplot(w_temp) + geom_point(aes(date, temp_max)) + facet_wrap(~StationName)
```

