---
title: "freezing_analysis"
author: "Shruti"
date: '2023-02-10'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read data - filter to stations of interest
```{r}
stations <- c("RRI", "CLL", "SRH", "GYS", "MRZ", "VER", "RIV", "JER")
tempdata <- readRDS("data_clean/Temp_filtered.rds") %>%
  filter(Station %in% stations)
latlons <- read.csv("https://portal.edirepository.org/nis/dataviewer?packageid=edi.591.2&entityid=a059f5eea4f8500fe1a43566451ec593")
```

# See stations
```{r}
sta_locations_sf <- latlons %>%
  filter(Station %in% stations) %>%
  st_as_sf(coords = c("Longitude", "Latitude"),
           crs = 4326)
  
mapview::mapView(sta_locations_sf, zcol = "Station")
```

# Add parameters
```{r}
dailytemp <- tempdata %>%
  group_by(Station, Date) %>%
  summarize(minTemp = min(Temp),
            meanTemp = mean(Temp),
            maxTemp = max(Temp)) %>%
  mutate(Month = month(Date),
         Year = year(Date),
         WY = ifelse(Month > 9, Year + 1, Year),
         Season = case_when(Month %in% c(10, 11, 12) ~ "Fall",
                            Month %in% c(1, 2,3) ~ "Winter",
                            Month %in% c(4, 5, 6) ~ "Spring",
                            Month %in% c(7, 8, 9) ~ "Summer")) %>%
  ungroup()
```
