---
title: "heatwave_analysis"
author: "Catarina Pien"
date: '2023-02-04'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Questions 
* Definitions of the baseline 
- Monthly station mean across years? Or delta-wide?



```{r}
library(dplyr)
library(lubridate)
library(tidyr)
library(ggplot2)
library(sf)
library(mapview)
```

# Read data - filter to stations of interest
```{r}
stations <- c("RRI", "CLL", "SRH", "GYS", "MRZ", "VER", "RIV", "JER")
tempdata <- readRDS("data_clean/Temp_filtered.rds") %>%
  filter(Station %in% stations)
latlons <- read.csv("https://portal.edirepository.org/nis/dataviewer?packageid=edi.591.2&entityid=a059f5eea4f8500fe1a43566451ec593")
```

# Make map
```{r}
sta_locations_sf <- latlons %>%
  filter(Station %in% stations) %>%
  st_as_sf(coords = c("Longitude", "Latitude"),
           crs = 4326)
  
mapview::mapView(sta_locations_sf, zcol = "Station")
```

# Add parameters
```{r}
dailytemp <- tempdata %>%
  group_by(Station, Date) %>%
  summarize(minTemp = min(Temp),
            meanTemp = mean(Temp),
            maxTemp = max(Temp)) %>%
  mutate(Month = month(Date),
         Year = year(Date),
         WY = ifelse(Month > 9, Year + 1, Year)) %>%
  ungroup()
```

# Look at data
```{r}
dailytemp %>%
  group_by(Station, Year) %>%
  summarize(n = n()) %>%
  ggplot() + geom_tile(aes(Year, Station, fill = n))
```

# Filter data

* May-September
* 2000 +
* Calculate the mean max, mean, min across all years for each station?
```{r}
summermeans = dailytemp %>%
  filter(Year>1999) %>%
  filter(Month %in% c(5, 6, 7, 8, 9)) %>%
  group_by(Station, Month) %>%
  summarize(meanMax = mean(maxTemp),
          meanMean = mean(meanTemp),
            meanMin = mean(minTemp)) %>%
  ungroup()

summertemp = dailytemp %>%
  filter(Year>1999) %>%
  filter(Month %in% c(5, 6, 7, 8, 9)) %>%
  group_by(Station, Month) %>%
  mutate(fYear = factor(Year) ,
         meanMax = mean(maxTemp),
          meanMean = mean(meanTemp),
            meanMin = mean(minTemp)) %>%
  ungroup()
```

# Calculate percentiles

# Plots
```{r}
ggplot(summertemp) + geom_boxplot(aes(fYear, meanTemp)) + facet_wrap(~Month) +
   theme_bw() + theme(axis.text.x = element_text(angle = 90))
ggplot(summertemp) + geom_boxplot(aes(fYear, maxTemp))+ facet_wrap(~Month)+ theme_bw() + theme(axis.text.x = element_text(angle = 90))
ggplot(summertemp) + geom_boxplot(aes(fYear, minTemp))+ facet_wrap(~Month)+ theme_bw() + theme(axis.text.x = element_text(angle = 90))
```

